// frontend/src/routes/login/+page.svelte
<script lang="ts">
  import { goto, invalidate } from '$app/navigation';
  import Button from '$lib/components/ui/button/button.svelte';
  import { Input } from '$lib/components/ui/input/index.js';
  import Label from '$lib/components/ui/label/label.svelte';
  import { bird, user } from '$lib/lib';
  import { onMount } from 'svelte';

  onMount(async () => {
    if ($user !== null) {
      goto('/collections');
    }
  });

  async function loginAction(e: SubmitEvent) {
    e.preventDefault();
    const form = e.target as HTMLFormElement;
    const formData = new FormData(form);
    const formObject = Object.fromEntries(formData.entries());

    await bird.auth.login(formObject.username, formObject.password);
    goto('/collections');
  }
</script>

<div>
  <h1>Login</h1>
  <form method="POST" class="w-2/3 space-y-6" onsubmit={loginAction}>
    <div class="flex w-full max-w-sm flex-col gap-1.5">
      <Label for="username">Username</Label>
      <Input id="username" name="username" />
    </div>
    <div class="flex w-full max-w-sm flex-col gap-1.5">
      <Label for="password">Password</Label>
      <Input id="password" name="password" type="password" />
    </div>

    <Button type="submit">Login</Button>
  </form>

  <p>No Account? <a href="/register">Register</a></p>
</div>

// frontend/app/src/pages/Login.tsx
import { useState, type FormEventHandler } from 'react';
import { NavLink } from 'react-router';
import { bird } from '../lib/lib';

const Login = () => {
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');

  const handleSubmit = (e: any) => {
    e.preventDefault();

    bird.auth.login(email, password);
  };

  return (
    <div className="flex flex-col justify-center items-center">
      <form onSubmit={handleSubmit}>
        <div>
          <label htmlFor="email">Email</label>
          <input
            className="input"
            value={email}
            type="text"
            id="email"
            onChange={(e) => setEmail(e.target.value)}
          />
        </div>
        <div>
          <label htmlFor="password">Password</label>
          <input
            className="input"
            value={password}
            type="password"
            id="password"
            onChange={(e: any) => setPassword(e.target.value)}
          />
        </div>
        <input
          className="btn btn-primary w-full mt-5"
          type="submit"
          value="Login"
        />
      </form>

      <p className="mt-5">
        <NavLink to="/register">No Account?</NavLink>
      </p>
    </div>
  );
};

export default Login;
