// frontend/src/routes/register/+page.svelte
<script lang="ts">
  import Button from '$lib/components/ui/button/button.svelte';
  import * as Form from '$lib/components/ui/form/index.js';
  import { Input } from '$lib/components/ui/input/index.js';
  import Label from '$lib/components/ui/label/label.svelte';
  import { bird } from '$lib/lib';

  async function loginAction(e: SubmitEvent) {
    e.preventDefault();
    const form = e.target as HTMLFormElement;
    const formData = new FormData(form);
    const formObject = Object.fromEntries(formData.entries());

    const user = { ...formObject, role: 0, disabled: false };
    await bird.collection('users').create(user);
  }
</script>

<div>
  <h1>Register</h1>
  <form method="POST" class="w-2/3 space-y-6" onsubmit={loginAction}>
    <div class="flex w-full max-w-sm flex-col gap-1.5">
      <Label for="username">Email</Label>
      <Input id="email" name="email" />
    </div>
    <div class="flex w-full max-w-sm flex-col gap-1.5">
      <Label for="username">Username</Label>
      <Input id="username" name="username" />
    </div>
    <div class="flex w-full max-w-sm flex-col gap-1.5">
      <Label for="password">Password</Label>
      <Input type="password" id="password" name="password" />
    </div>
    <div class="flex w-full max-w-sm flex-col gap-1.5">
      <Label for="password">Confirm Password</Label>
      <Input type="password" id="confirmPassword" name="confirmPassword" />
    </div>

    <Button type="submit">Register</Button>
  </form>

  <p>Already have an account? <a href="/#/login">Login</a></p>
</div>

// frontend/app/src/pages/Register.tsx
import { useState } from 'react';
import { bird } from '../lib/lib';

const Register = () => {
  const [email, setEmail] = useState<string>('');
  const [username, setUsername] = useState<string>('');
  const [password, setPassword] = useState<string>('');
  const [confirmPassword, setConfirmPassword] = useState<string>('');

  const handleSubmit = async (e: any) => {
    e.preventDefault();

    await bird.collection('users').create({
      email: email,
      username: username,
      password: password,
      disabled: false,
      role: 5,
    });
  };

  return (
    <div className="flex flex-col justify-center items-center">
      <form onSubmit={handleSubmit}>
        <div>
          <label htmlFor="email">Email</label>
          <input
            className="input"
            value={email}
            type="text"
            id="email"
            onChange={(e) => setEmail(e.target.value)}
          />
        </div>
        <div>
          <label htmlFor="username">Username</label>
          <input
            className="input"
            value={username}
            type="text"
            id="username"
            onChange={(e) => setUsername(e.target.value)}
          />
        </div>
        <div>
          <label htmlFor="password">Password</label>
          <input
            className="input"
            value={password}
            type="password"
            id="password"
            onChange={(e) => setPassword(e.target.value)}
          />
        </div>
        <div>
          <label htmlFor="confirmPassword">Confirm Password</label>
          <input
            className="input"
            value={confirmPassword}
            type="password"
            id="confirmPassword"
          />
        </div>
        <input
          type="submit"
          value="Register"
          className="btn btn-primary w-full mt-10"
        />
      </form>
    </div>
  );
};

export default Register;
